eureka:
  client:
    serviceUrl:
#     服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/
#0 端口随机
server:
  port: 0
spring:
  application:
#   服务与服务之间相互调用一般都是根据这个name
    name: order-service
#zipkin
  zipkin:
    base-url: http://localhost:9411


