#服务注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.20.55.5:8761/eureka/
#服务的端口
server:
  port: 8769
#服务名
spring:
  application:
    name: service-zuul

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    feign-server:
#以/feign开头的请求都转发给service-feign服务
      path: /feign/*
      serviceId: feign-server
    auth-service:
      path: /auth/**
      serviceId: auth-service
    user-service:
      path: /user/**
      serviceId: user-service