eureka:
  client:
    serviceUrl:
#     服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/
#为0 端口随机
server:
  port: 0

#zipkin
  zipkin:
    base-url: http://localhost:9411
spring:
  application:
#   服务与服务之间相互调用一般都是根据这个name
    name: user-service
  datasource:
      name: test
      url: jdbc:mysql://127.0.0.1:3306/xiaofangyuan?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      url: jdbc:mysql://rm-wz92a6yw952x0zgxnfo.mysql.rds.aliyuncs.com:3306/xiaofangyuan?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
#      password: Xiaofangyuan123
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
#bus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#springcloud-bus
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]
  cloud:
    bus:
      trace:
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fangyuanyouyue.user.model

mapper:
  mappers:  com.fangyuanyouyue.user.dao
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
##断路器开关
#feign:
#    hystrix:
#        enabled: true
##防止springboot2.0以上出现Unable to connect to Command Metric Stream
##默认其实的切入点是：/actuator/hystrix.stream 要改成/hystrix.stream
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#base-path: /
