eureka:
  client:
    serviceUrl:
#     服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
#   服务与服务之间相互调用一般都是根据这个name
    name: service-hi
#zipkin
  zipkin:
    base-url: http://localhost:9411
#config-client
#  cloud:
#    config:
##     指明远程仓库的分支
#      label: master
##     dev开发环境配置文件 test测试环境 pro正式环境
#      profile: dev
##     指明配置服务中心的网址。
#      uri: http://localhost:8888/


